### ISSUE TITLE
portals can crash the game

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/snakefall#10]
If you put two portals (teleporters) directly above one another with a clear path between them, you can fall infinitely. This crashes the game by tying up the javascript thread in an infinite loop.

My proposal is to disable portals that are directly above one another with no wall/spike between them.

**Comment by XeroOl** [comment]
don't allow the move if it uses the portal multiple times AND the portals are directly above one another

**Comment by thejoshwolfe** [comment]
What do you mean by "don't allow the move"? Do you mean look ahead to see what would happen? That's hard to program. It's doable, but I'd like to consider other options first.

Another possible solution is to detect infinite loops, and simply declare you dead (of starvation perhaps). Then you'd be forced to undo the move and try something else.

**Comment by XeroOl** [comment]
"Then you'd be forced to undo the move and try something else." If you make it auto-undo, then it would appear to the user as if the snake can't move into the infinite loop.

**Comment by XeroOl** [comment]
Another solution: when animations are added, allow undo during the animation

**Comment by Patashu** [comment]
Hacky fix: If portals activate 100 times in the same move, stop activating portals for the rest of the move.

**Comment by thejoshwolfe** [comment]
I think I like the detecting infinite moves and declaring you dead solution the best. It would simply require storing a serialization of the game state after each gravity tick, testing if we've already seen that state during the current move. Not too hard to implement, and things like that would be necessary for the solver AI in #5, so it's something that we want to be able to do anyway.

Now that we have animations, I think the You Dead message plus the animation of falling infinitely will get the point across, and i think it's the most obvious and elegant solution to the problem. It's effectively equivalent to the other ideas here like "don't allow the move" and auto-undo, but it still shows the player why the move is a bad idea.

**Comment by thejoshwolfe** [comment]
[This puzzle](http://wolfesoftware.com/snakefall/#level=HyRr4JK1&17&31?*z0*z0*z0*704*J011*P0*01*O011*I05*201*101*D05*2010100011*B0*3100011*3011*50*I1*50*510*71*70*4100*61*70*31000*61*10/s0?351&350&349/f0?328/f1?366/s1?347/) demonstrates the infinite loop death situation.
