### ISSUE TITLE
multiple objects falling through a portal in a single move causes non-deterministic behavior

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/snakefall#12]
The physics engine checks if multiple objects are falling all together so that objects cannot recursively support one another. This is good. We also need something similar for objects blocking other objects from going through portals.

If a snake holding a block jumps into a portal, the snake will go through unobstructed while the block is poised 1 square above the portal. Now the snake and the block are supposed to fall at the same time. If we check the snake first, the snake gets out of the way so that the block can take the portal as you would expect. If we check the block first, the block will fail to go through the portal because the snake hasn't fallen out of the way yet. This is broken.

I've personally experienced this bug.

**Comment by XeroOl** [comment]
after something lands, update all the objects so the block won't hover over the portal.

**Comment by XeroOl** [comment]
Think about level setups like [this one](http://wolfesoftware.com/snakefall/#level=3tFRIoTU&11&10?*N05*J01*A0*01*005*V0/s0?43&42&41/b0?53&54&44&34&33/). What is the intended behavior here?

**Comment by thejoshwolfe** [comment]
For that example:
* the block takes the portal.
* both objects fall 1 space.
* the snake takes the portal, because there's just enough space for the snake to fit inside the block.
* both fall 1 space again.
* the block takes the portal, falling to its death. the snake lands safely.

Thanks for the test case. That was a perfect example of how the game is wrong.

**Comment by XeroOl** [comment]
[Another](http://wolfesoftware.com/snakefall/#level=3tFRIoTU&14&10?*l01*001*D05*D05*X0*61/s0?44&43&42&41/b0?54&55&45&35&33/) example to show that its broken. The snake should stay inside the block frame but instead skips the top portal.
