### ISSUE TITLE
Spikes look bad when they are floating

### ISSUE THREAD

**Issue by XeroOl** [thejoshwolfe/snakefall#13]
The spike graphic appears as if its attached on the bottom, even if the spike is floating. This makes mid-air spikes look bad. Think about how level 1-Star would look if it was recreated with this editor.

**Comment by thejoshwolfe** [comment]
try it now.

**Comment by thejoshwolfe** [comment]
be sure to refresh the page to get the new code.

**Comment by XeroOl** [comment]
I saw the green ground and blue sky thing and it was really pretty. Whatever algorithm you used for the grass outline would probably look good on boxes (be sure to hide connecting wires when they're inside a block)

**Comment by XeroOl** [comment]
Also it has the old code rn
