### ISSUE TITLE
Pushing block into tail

### ISSUE THREAD

**Issue by XeroOl** [thejoshwolfe/snakefall#18]
I am aware that pushing a block into the snake's tail [like this](http://wolfesoftware.com/snakefall/#level=3tFRIoTU&12&17?*z0*M04*R0*11*8010001*801000111*601*C0*31*20/b0?176&180/s0?160&159&158/) is intended. However, it seems incorrect when your tail isn't moving directly away from the block [like this](http://wolfesoftware.com/snakefall/#level=3tFRIoTU&8&11?*E04*4021112*2011011*2010001*601*00*31*80/b0?62/s0?59&58&57&56&67/)

**Comment by thejoshwolfe** [comment]
I programmed those mechanics to work the same as in the original game. You can try it out on levels 8 and 25.

**Comment by XeroOl** [comment]
btw i solved the ordeal. took forever though. nice level!

**Comment by thejoshwolfe** [comment]
Thanks. I've only solved the first 3 of yours. You make pretty good levels.

**Comment by andrewrk** [comment]
Looks like level discussion is something that at least two people would benefit from

**Comment by andrewrk** [comment]
A place to discuss levels I mean.

**Comment by XeroOl** [comment]
yeah it probably would benifit people. Also, "please add animations" was a joke level. It can be solved in 2 moves. You might want to go back and look at it.
