### ISSUE TITLE
Color blocks differently from one another

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/snakefall#20]
See #17 for discussion.

This would especially help for situations [like this](http://wolfesoftware.com/snakefall/#level=3tFRIoTU&17&31?*z0*z0*z0*z0*n04*z0*D03*20*51001110011100*31*70*A1*z0*20/s4?380&379&378&377/b0?383&388/b1?385&390/s1?349&348/).

**Comment by XeroOl** [comment]
made a pull request

**Comment by XeroOl** [comment]
How I would go about changing the render code for transparent boxes:
1) render the connectors
2) render sky color where boxes are, so you don't see connector through them.
3) render the tiles
4) draw the box outlines

**Comment by XeroOl** [comment]
Ok got transparency in the game. I did it the correct way. No sky colors, it just doesn't render the connectors where the block outlines will be.
