### ISSUE TITLE
When snakes die in certain conditions, Undo doesn't work properly.

### ISSUE THREAD

**Issue by XeroOl** [thejoshwolfe/snakefall#27]
When moving the red snake up in [this level](http://wolfesoftware.com/snakefall/#level=HyRr4JK1&6&5?*C02*00201000200/s0?17&18/s1?11&12/), both the snakes die. If you undo that move, the green snake stays dead. However, it should be alive.

**Comment by thejoshwolfe** [comment]
Great work finding this bug and giving a minimal example that reproduces it. That really helps to find the problem! This was a really subtle bug that's been in the undo logic since it was first written.
