### ISSUE TITLE
Arbitrarily many blocks and snakes

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/snakefall#4]
Currently, you're limited to 4 blocks and 4 snakes.

**Comment by XeroOl** [comment]
Snake colors could repeat after 4 snakes. Boxes may need a color overhaul.

**Comment by thejoshwolfe** [comment]
I'm totally open to a color overhaul. It would also be kind of cool to show the outlines of the blocks like in Snakebird rather than showing them as solid colors, but that's a little complicated to program.

Did you have any ideas for block colors? Like maybe use brighter colors? Maybe put some graphic in the middle of them, like a circle of a different color, to help identify them as blocks?

**Comment by XeroOl** [comment]
Right now, all blocks are different shades of red, which can make it difficult to tell blocks apart.
I would just give them different colors. Judging off of the colors in level 29, i would suggest something like this: 

R=255(FF) G=255*(BlockID-TotalBlockCount)/TotalBlockCount B=0

where BlockID is the index of the block starting at 0, and TotalBlockCount is the total amount of blocks.
This would generate a spectrum from yellow to red-ish, but wouldn't ever be 100% red.

**Comment by XeroOl** [comment]
Currently, the snake drawing tool only draws one color of snake until you toggle it. Can you change it so that the colors rotate by default, and the user can choose to toggle it back? That would be cool! Thanks!

**Comment by thejoshwolfe** [comment]
yeah. i was considering doing that. i think it's a good idea.

while we're on the subject, what inputs do you use to switch snakes. I've come to prefer number keys myself.

**Comment by thejoshwolfe** [comment]
Well, actually, now i don't like the idea of automatically switching snakes in the editor. it will behave strangely with undo/redo. If you place a red snake, undo, then place another snake, it should be red again. That means that undoing the snake placement should also switch the snake color back. But that gets complicated when you also switch to another snake color deliberately and then undo, and what if there are multiple edits after the snake placement in the undo buffer, and you undo back through all of them. Hm. I think maybe just expecting the user to always switch snakes deliberately makes more sense.
