### ISSUE TITLE
https://wolfesoftware.com/snakefall/experimental/ is a dead link

### ISSUE THREAD

**Issue by Patashu** [thejoshwolfe/snakefall#40]
403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: BD7C4CF4B5F3AD17
HostId: rdQJQE+pYLm0jp7UoUr9IUXe9aXSGB+CqfVRCz0pcCLiQ7GvBh6HKuBrzjycp1WRi+ArbderNEM=

**Comment by thejoshwolfe** [comment]
oh yeah. the automatic directory listing was lost when i switched hosting providers. i made an index manually and publish it:

https://wolfesoftware.com/snakefall/experimental/

thanks for point this out.

**Comment by Patashu** [comment]
Thanks for the fix!
