### ISSUE TITLE
Can't Finish Temple

### ISSUE THREAD

**Issue by jmdiamond3** [thejoshwolfe/snakefall#42]
The Snakefall level Temple doesn't seem to be solvable. I was able to get every fruit but I'm one snake segment short of reaching an exit. Am I doing something wrong or did Joel forget a fruit?

**Comment by thejoshwolfe** [comment]
Bruh. I can only solve like half the community contributed levels.

This inspires me to work on #5 though, which should determine once and for all if and how people's levels are solvable.

**Comment by Patashu** [comment]
Another good solution would be a replay system. (And then going around and bugging level creators to create replays for their levels.)

**Comment by XeroOl** [comment]
I would love to see a replay system. I'm imagining that there could be a way to verify that a replay solves the puzzle without actually watching the replay.

**Comment by thejoshwolfe** [comment]
See #9 for replays.

**Comment by thejoshwolfe** [comment]
replays are working now. here's me solving one of @XeroOl 's levels:

[Turn Around - josh's solution](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&9&14?*A01*90111*70*112*40100011*40104001*401*001*40111*70*210012*00/s0?103&102&88&74/s1?101&87&73&59/#replay=nmGTi8PB&rrruu1rrruruuruulddldl0luurddl1luul0llluull)

**Comment by XeroOl** [comment]
Should I go through and make a replay link for the levels?

**Comment by jmdiamond3** [comment]
The replay is a great idea. I can do a few replays of levels I've completed.

I can't do "Level 1" by DoctorEndugu or "Level 3 'The Servant'" by Teal Knight, but I think I've completed all of the other levels that aren't "fruit maze" style. I don't like those and have no interest in attempting them.

**Comment by jmdiamond3** [comment]
I saw someone couldn't complete this, so I made a replay: [Spike Maze](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&17&25?*70111*I0141*I0101000*01*B01010001001*B01011001001*00*8100*0100111*K010011000202*2021102020*010002*B010001102010001*5010012011010001*101*5010110020002001000201210200011*901*30201102021002*5022010011*902*402110001221*002111*00*412*0122*3122*21/b3?351&363/s1?386&385&384&383/s0?391&392&393&394/f0?119/#replay=nmGTi8PB&1ulllu*1ldll0ulu*0lddl1u0uurrru1*5rdrurruu0ulurrrulll1u0lurrdrrr1lldlllulluu0ururrddl1luuu0luldl1rru*4rurrr0dddrdrrrulllululldlldllulluulluuurru*8ruu*4l1uurrddllluu*6ldrdr0dddluuul1druruu*1ldddrrddrr0u*0l1drrulllu*3ldrru0*0lddr1*4r0u*3rurrrulll1urruu*0l0ddru1dr0ruurru1ru0ulluulldddr1ul0uuruuu1uurulldluu0ldllulluuluuurrurrurull1llurrddluul0ull1u*1r0llu*5ru1rrrururr*0uluurddd*3l0u*7l1uulllulll0u*0r1llu*5ruurruul0*3ru1*1lul*0u0ulluu*0lul*0u)

**Comment by thejoshwolfe** [comment]
I've created a [Solutions](https://github.com/thejoshwolfe/snakefall/wiki/Solutions) page on the wiki for community-contributed replays. I've ported the two mentioned here as a start.
