### ISSUE TITLE
Solution: The Ordeal

### ISSUE THREAD

**Issue by jmdiamond3** [thejoshwolfe/snakefall#44]
[One of my favorites](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&23&29?*Q1*02*30124001*20*02112*60122201*50211*701*001*6011*701*001004*3011*701*001*6011*402001*001*20110011*70122001*6011*70120001*6011*701*001*20110011221001*10102221*50111*6011*001*6011*701*001*60111001*30122021*401211*50101*00111*4011*701*001*6011212021011001*001*301221100202*201*001001*301100242*101100101*601100222*201*001*20122211*401001*00111*4011*701*00111*40*Q1/b0?188&194&182/b1?596&588&604/s0?620&619&618&617/s2?632&631&630&629/s1?625&624&623&622/f0?246/#replay=nmGTi8PB&2rrrulll0uulllddll1ululluuruuru0uuu2llluuluuurrdruruuuruuuruuldddl1rulld2u1dr2u1uu0rruurruuruu*0luu2ruuuruuuruuurullurrdldd*2luuluuuruuuluururullddrru0*1luuulu*0ruu2rruuuruuuruuuruuuru*3ldr0luuulurrrullldrrr2rruuuruuuruuuruuuru*0luuuru*0l0urruu2ld*1ruuuruuuruuuru*0luuuru*0ldr0lu*0rdlluruuuru*0lullddrrdrrrulllul2ddluuluuuruuuruuu0*0luuulurrruuulurrrullldrrr2rddd0urr1luu0dddr1rur0uulldddrrruuluru2luuulluuurrdr0ruulluurrdddl1uluu0u2ruuuruuuru*0lurrdlllu1ul2ul*0urru1l2u1u0uluu2luuuluuurrrdlluuluuuruuuluurrdlluruuul1ururruuu0ruuuru*0lu2uuu0lddrruru*0ldrru2*1ruuuruuuruuuru*0l0*0lu*2ruuruuuruu*1luuur2uu0rulldrrruuruuuruuluurddluu2lurur1ll2rdll0ruullldl2ddrrrullldl0llddr2dldldrrr0rrrdllullddd2ruuuruuuruuuru*3l*0u)

**Comment by thejoshwolfe** [comment]
I've created a [Solutions](https://github.com/thejoshwolfe/snakefall/wiki/Solutions) page on the wiki for community-contributed replays. Please move your solution to there.
