### ISSUE TITLE
Solution: Level 4 "Greed that goes well"

### ISSUE THREAD

**Issue by jmdiamond3** [thejoshwolfe/snakefall#45]
[Solution](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&17&31?*81*50*I1*50*I1*50*I1*50*I1*50*I1*50*I1*004*00111000*C1*501*30*21*D01011*00*1100110011*801*10*0100*31*60111*10*01*F0111*02*112101001112*50*A10122*01*001*00*A10*31*001*00*91*901*00*910*11011*50*61/b2?257&313&256/s1?357/s2?326/s0?388/s3?295/f1?253/f11?470/b1?283&475&469/b0?512&350&351/f12?476/f0?239/f3?300/f2?258/f10?389/f4?325/f5?327/f8?358/f7?356/f9?387/#replay=nmGTi8PB&lu1ru0rr2luruld1lulul2rur0ull2ul1uruu*2ruu*0ru*0ldd*2l3ll2lul0uu1lurrdddl0r1l0r1lurr0ulll3lll0ll3l2lullulu*3l3*1r1ullldrrulluldll2dlddrddd*3r1uu2r1lurrr3l1uuur3r1uulll3*1l1lulu*3l2rruruurrru*0l1dldd*6r3*1r1urr2urruluu3u1rrrdddll2ruuu0uruuuru1*2u)

**Comment by thejoshwolfe** [comment]
I've created a [Solutions](https://github.com/thejoshwolfe/snakefall/wiki/Solutions) page on the wiki for community-contributed replays. Please move your solution to there.
