### ISSUE TITLE
Solution: Level 6 "Decisions"

### ISSUE THREAD

**Issue by jmdiamond3** [thejoshwolfe/snakefall#46]
[Solution](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&17&31?*21*50*D1000111*C04111000*510*3122022*71*D02*7011*P011*P011*301*901*3011*3011*7011*3011*301*901*3011*3011100*1100111*3011*30*B1*3011*40*91*4011*P011*P01120222*F022202140011*H211004*R1/b2?6&7&8&48&9&10&11&12&13/b1?59&429&430&431/b0?33&405&406&407/s1?257/s2?269/s0?263/f11?494/f0?53/f14?52/f8?397/f10?467/f5?377/f7?236/f12?237/f6?235/f1?227/f2?228/f3?229/f4?232/#replay=nmGTi8PB&1ru*0ru*0ru*2l2lu*0lu*1ldr0lll2ull0ll1lullu*4ld*1ru*1lurrrur2uul0l2ull0ll2ll0ll2ll0l2dr1ruulll2r0r1dll2ull1*0d2uu0l2ruu1rrur2r1*3u2rrr1*4rdddllluul2r1ul2uluu1u2*Br0*1l1*8ruuu*5rd*1lu*1rdlddrr)

**Comment by thejoshwolfe** [comment]
I've created a [Solutions](https://github.com/thejoshwolfe/snakefall/wiki/Solutions) page on the wiki for community-contributed replays. Please move your solution to there.
