### ISSUE TITLE
Solution: Balancing Act

### ISSUE THREAD

**Issue by jmdiamond3** [thejoshwolfe/snakefall#47]
[Solution](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&17&31?*01*M011011*J0*11*N0*0101110001*G01110111*L011011*M011*P011*P01101*N0*01*9011*80*11*70*01*101*10*11*70*0100*01*10*01*101001*0011*0011*20111*201001*704*20111*201001*402*50111*201001*701*20111*201001*701*201/b0?299&294/f0?416/f3?153/b1?390&219&188/s0?64&63&32/s1?265&266&297/s2?28&29/f1?148/#replay=nmGTi8PB&1u*2rurr2*0l1ulluuruu2u1ullddlll2*0l1ul2u*1lur1ullu*5l0*6r1u*0ruuu0*0rul2r1rulluu0l2r0ld2u0r2*0l1rr2ll1ruuluuulu*1r0ur1*1r0*1r1rr0urdrrrulllulldrrrurrull1uluruuu*2r*0u*1l0urd1*1l0*1l1ul0ulll1ulu*2l0*4l1*1l2u*0l1u2u1r2l1rr0lllurrrdrdrru1r0llu2llur0*0lull2*0r0urrruur1uu2ul0rul1ululu0ul2ll0ul1u2*1lur0ur1rrr0*0rdd2urr0r1rrdruuuldlullddlllurrr0u*2l2*0r0ur1r2*0r0urrr1uuururrullldddluur0rulldrrur1ululllu0rulldrurr1*0rddldluuluuurr2*1r1rrurrrdrdddrdrd*0ru2*2r0rrddrdrrr1ll)

**Comment by thejoshwolfe** [comment]
I've created a [Solutions](https://github.com/thejoshwolfe/snakefall/wiki/Solutions) page on the wiki for community-contributed replays. Please move your solution to there.
