### ISSUE TITLE
Solution: Level 5 "Collapse"

### ISSUE THREAD

**Issue by jmdiamond3** [thejoshwolfe/snakefall#48]
[Solution](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&17&31?*01*20*L1*405*I1*20*L1*B0104*91*B010*A1*B01*00*71*B01101*00*41*G0100*L10*81*50*51*505111*50*51*60111*50*51*60111*50*51*601112*2020*51*601112*2022*51*601*A04002*80*01*20101101*12*60/b0?4&407/b1?5&377/b2?6&378/b7?468&375&344&313&282/b8?478&175/b3?7&472/b4?8&442/b5?9&443/b6?35&36&37&38&39&40&42/s0?166&167&168&169&170&171&172&173&204&203&202&201&200&199&198&197&196&227&228&229&230&231&232&233&234&235/s1?41/s2?467/f0?113/f1?236/f2?243/f3?477/#replay=nmGTi8PB&lldd*1lurulurulurrrdrrdrrdlldd*1lurrrulllu1r2*9r0uuu*0rdddrrdddr1ll*Arurrrdlullullluur0*6ruuluur)

**Comment by XeroOl** [comment]
I don't think issues is where you should be posting these. Maybe a separate page on the wiki?

**Comment by thejoshwolfe** [comment]
I've created a [Solutions](https://github.com/thejoshwolfe/snakefall/wiki/Solutions) page on the wiki for community-contributed replays. Please move your solution to there.
