### ISSUE TITLE
Close this "issue", just please put this level on the wiki, thank you!

### ISSUE THREAD

**Issue by eff96** [thejoshwolfe/snakefall#53]
https://wolfesoftware.com/snakefall/#level=HyRr4JK1&17&23?*91*601*3010541*6010*11010111*601*1010101*80*11010101*801*1010001*8010*51*80101*301*605010*3101*801*501*80*71*z0*w0*J1/s6?262&261&260&259&258&257&256&255&254&253&276&299&322&345&346&347&348&349&350&351&352&353&354&331&308&285&284&283&282&281&280&279&278&277&300&323&324&325&326&327&328&329&330&307&306&305&304&303&302&301/

I name it, 'FIT IN'.

**Comment by XeroOl** [comment]
anybody with a github account should have write access to the wiki
