### ISSUE TITLE
disable holding arrow keys

### ISSUE THREAD

**Issue by eff96** [thejoshwolfe/snakefall#55]
it instantly creates HUGE lag, there are two very important cases where you think you're in the verge of crashing:

- [holding up](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&4&3?*010110*01/s0?7/)
- [holding left or right next to a portal](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&4&3?05*00500111/s1?7&8/)
- [holding left or right to move great lengths which can result in bad levels](https://wolfesoftware.com/snakefall/#level=HyRr4JK1&2&260?*z0*z0*z0*y04*z1*z1*z1*z1/s3?1&0/)

**Comment by JoeltheFox** [comment]
But you can just avoid those scenarios. And it's nice to move quickly when needed

**Comment by thejoshwolfe** [comment]
I didn't experience any lag in those examples. I don't think the input is to blame for "bad levels" like you posted.

If you're experiencing lag, then maybe there's an optimization that can be made. It you'd like to post an issue about optimizing lag, then open a new issue and be sure to note which browser and OS you're using (and an example level would be nice too).
