### ISSUE TITLE
ability to share replays

### ISSUE THREAD

**Issue by thejoshwolfe** [thejoshwolfe/snakefall#9]
Currently, you can watch a replay of your solution by holding the undo and redo keys. It would be cool to be able to share replays in a url to show a friend "this is how far I got", or "i beat it in fewer moves than you", or "did you know you can get over here", etc.

**Comment by XeroOl** [comment]
or proving a level is possible

**Comment by thejoshwolfe** [comment]
I also have big dreams of using #5 to prove levels are solvable.

**Comment by XeroOl** [comment]
i think if you embed a solution into the url, you can make it warn you if the solution doesn't work or if the url has no solution.

**Comment by XeroOl** [comment]
#5 would be really cool cause i could build solvable levels without knowing how to solve them.

**Comment by thejoshwolfe** [comment]
> i could build solvable levels without knowing how to solve them.

I've totally done that. :) It's an interesting experience trying to solve a level without knowing if it's solvable at all. The [halting problem](https://en.wikipedia.org/wiki/Halting_problem) comes to mind.

**Comment by XeroOl** [comment]
Well I would also like to share the intended solutions to my puzzles to prove they are possible.

**Comment by thejoshwolfe** [comment]
Yeah, like for Spike Maze. I cannot figure that one out. I even tried turning off gravity a few times just to explore the possibilities and still ran into one dead end after another. Levels too difficult for me to solve are motivation to make the solver AI too.
